// Generated by scripts/gen-db-types.mjs from supabase/migrations. Don't edit
// by hand: change a migration, then run `npm run db:types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "12"
  }
  public: {
    Tables: {
      artist_ratings: {
        Row: {
          artist_mbid: string
          created_at: string
          id: number
          review: string | null
          score: number
          updated_at: string
          user_id: string
        }
        Insert: {
          artist_mbid: string
          created_at?: string
          id?: never
          review?: string | null
          score: number
          updated_at?: string
          user_id: string
        }
        Update: {
          artist_mbid?: string
          created_at?: string
          id?: never
          review?: string | null
          score?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "artist_ratings_artist_mbid_fkey"
            columns: ["artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "artist_ratings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      artists: {
        Row: {
          albums_cached_at: string | null
          bio: string | null
          cached_at: string
          image_url: string | null
          mbid: string
          name: string
          popularity: number | null
          search_names: string | null
          seed_score: number | null
          seed_source: string | null
          seed_votes: number | null
        }
        Insert: {
          albums_cached_at?: string | null
          bio?: string | null
          cached_at?: string
          image_url?: string | null
          mbid: string
          name: string
          popularity?: number | null
          search_names?: string | null
          seed_score?: number | null
          seed_source?: string | null
          seed_votes?: number | null
        }
        Update: {
          albums_cached_at?: string | null
          bio?: string | null
          cached_at?: string
          image_url?: string | null
          mbid?: string
          name?: string
          popularity?: number | null
          search_names?: string | null
          seed_score?: number | null
          seed_source?: string | null
          seed_votes?: number | null
        }
        Relationships: []
      }
      follows: {
        Row: {
          created_at: string
          follower_id: string
          following_id: string
        }
        Insert: {
          created_at?: string
          follower_id: string
          following_id: string
        }
        Update: {
          created_at?: string
          follower_id?: string
          following_id?: string
        }
        Relationships: []
      }
      invites: {
        Row: {
          code: string
          created_at: string
          user_id: string
        }
        Insert: {
          code?: string
          created_at?: string
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "invites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      list_items: {
        Row: {
          added_at: string
          list_id: number
          note: string | null
          position: number
          release_mbid: string
        }
        Insert: {
          added_at?: string
          list_id: number
          note?: string | null
          position: number
          release_mbid: string
        }
        Update: {
          added_at?: string
          list_id?: number
          note?: string | null
          position?: number
          release_mbid?: string
        }
        Relationships: [
          {
            foreignKeyName: "list_items_list_id_fkey"
            columns: ["list_id"]
            isOneToOne: false
            referencedRelation: "lists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "list_items_release_mbid_fkey"
            columns: ["release_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
        ]
      }
      lists: {
        Row: {
          created_at: string
          description: string | null
          id: number
          ranked: boolean
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: never
          ranked?: boolean
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: never
          ranked?: boolean
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lists_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      mixtape_picks: {
        Row: {
          created_at: string
          kind: string
          mbid: string
          month: string
          user_id: string
        }
        Insert: {
          created_at?: string
          kind: string
          mbid: string
          month: string
          user_id: string
        }
        Update: {
          created_at?: string
          kind?: string
          mbid?: string
          month?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mixtape_picks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string | null
          id: string
          raised_era: string | null
          raised_on_mbid: string | null
          raised_scene: string | null
          record_colors: string[] | null
          username: string
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          raised_era?: string | null
          raised_on_mbid?: string | null
          raised_scene?: string | null
          record_colors?: string[] | null
          username: string
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          raised_era?: string | null
          raised_on_mbid?: string | null
          raised_scene?: string | null
          record_colors?: string[] | null
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_raised_on_mbid_fkey"
            columns: ["raised_on_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
        ]
      }
      rate_limits: {
        Row: {
          bucket: string
          hits: number
          subject: string
          window_start: string
        }
        Insert: {
          bucket: string
          hits?: number
          subject: string
          window_start: string
        }
        Update: {
          bucket?: string
          hits?: number
          subject?: string
          window_start?: string
        }
        Relationships: []
      }
      ratings: {
        Row: {
          created_at: string
          id: number
          release_mbid: string
          review: string | null
          score: number
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          release_mbid: string
          review?: string | null
          score: number
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: never
          release_mbid?: string
          review?: string | null
          score?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ratings_release_mbid_fkey"
            columns: ["release_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "ratings_user_id_profiles_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          artist_rating_id: number | null
          created_at: string
          id: number
          rating_id: number | null
          user_id: string
          value: number
          versus_take_id: number | null
          versus_vote_id: number | null
        }
        Insert: {
          artist_rating_id?: number | null
          created_at?: string
          id?: never
          rating_id?: number | null
          user_id: string
          value: number
          versus_take_id?: number | null
          versus_vote_id?: number | null
        }
        Update: {
          artist_rating_id?: number | null
          created_at?: string
          id?: never
          rating_id?: number | null
          user_id?: string
          value?: number
          versus_take_id?: number | null
          versus_vote_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reactions_artist_rating_id_fkey"
            columns: ["artist_rating_id"]
            isOneToOne: false
            referencedRelation: "artist_ratings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_rating_id_fkey"
            columns: ["rating_id"]
            isOneToOne: false
            referencedRelation: "ratings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_versus_take_id_fkey"
            columns: ["versus_take_id"]
            isOneToOne: false
            referencedRelation: "versus_takes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_versus_vote_id_fkey"
            columns: ["versus_vote_id"]
            isOneToOne: false
            referencedRelation: "versus_votes"
            referencedColumns: ["id"]
          },
        ]
      }
      releases: {
        Row: {
          artist_credit: string | null
          artist_mbid: string | null
          cached_at: string
          cover_art_url: string | null
          details_cached_at: string | null
          genres: string[]
          mbid: string
          popularity: number | null
          release_date: string | null
          seed_score: number | null
          seed_source: string | null
          seed_votes: number | null
          title: string
          tracks_cached_at: string | null
        }
        Insert: {
          artist_credit?: string | null
          artist_mbid?: string | null
          cached_at?: string
          cover_art_url?: string | null
          details_cached_at?: string | null
          genres?: string[]
          mbid: string
          popularity?: number | null
          release_date?: string | null
          seed_score?: number | null
          seed_source?: string | null
          seed_votes?: number | null
          title: string
          tracks_cached_at?: string | null
        }
        Update: {
          artist_credit?: string | null
          artist_mbid?: string | null
          cached_at?: string
          cover_art_url?: string | null
          details_cached_at?: string | null
          genres?: string[]
          mbid?: string
          popularity?: number | null
          release_date?: string | null
          seed_score?: number | null
          seed_source?: string | null
          seed_votes?: number | null
          title?: string
          tracks_cached_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "releases_artist_mbid_fkey"
            columns: ["artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          detail: string | null
          id: number
          reason: string
          reported_artist_rating_id: number | null
          reported_list_id: number | null
          reported_profile_id: string | null
          reported_rating_id: number | null
          reported_versus_take_id: number | null
          reporter_id: string
          status: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: never
          reason: string
          reported_artist_rating_id?: number | null
          reported_list_id?: number | null
          reported_profile_id?: string | null
          reported_rating_id?: number | null
          reported_versus_take_id?: number | null
          reporter_id: string
          status?: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: never
          reason?: string
          reported_artist_rating_id?: number | null
          reported_list_id?: number | null
          reported_profile_id?: string | null
          reported_rating_id?: number | null
          reported_versus_take_id?: number | null
          reporter_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_reported_artist_rating_id_fkey"
            columns: ["reported_artist_rating_id"]
            isOneToOne: false
            referencedRelation: "artist_ratings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_list_id_fkey"
            columns: ["reported_list_id"]
            isOneToOne: false
            referencedRelation: "lists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_profile_id_fkey"
            columns: ["reported_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_rating_id_fkey"
            columns: ["reported_rating_id"]
            isOneToOne: false
            referencedRelation: "ratings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_versus_take_id_fkey"
            columns: ["reported_versus_take_id"]
            isOneToOne: false
            referencedRelation: "versus_takes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      song_ratings: {
        Row: {
          created_at: string
          id: number
          release_mbid: string
          score: number
          song_mbid: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          release_mbid: string
          score: number
          song_mbid: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: never
          release_mbid?: string
          score?: number
          song_mbid?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_ratings_release_mbid_fkey"
            columns: ["release_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "song_ratings_song_mbid_fkey"
            columns: ["song_mbid"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "song_ratings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      songs: {
        Row: {
          cached_at: string
          duration_ms: number | null
          mbid: string
          title: string
        }
        Insert: {
          cached_at?: string
          duration_ms?: number | null
          mbid: string
          title: string
        }
        Update: {
          cached_at?: string
          duration_ms?: number | null
          mbid?: string
          title?: string
        }
        Relationships: []
      }
      top_albums: {
        Row: {
          created_at: string
          position: number
          release_mbid: string
          user_id: string
        }
        Insert: {
          created_at?: string
          position: number
          release_mbid: string
          user_id: string
        }
        Update: {
          created_at?: string
          position?: number
          release_mbid?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "top_albums_release_mbid_fkey"
            columns: ["release_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "top_albums_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      top_artists: {
        Row: {
          artist_mbid: string
          created_at: string
          position: number
          user_id: string
        }
        Insert: {
          artist_mbid: string
          created_at?: string
          position: number
          user_id: string
        }
        Update: {
          artist_mbid?: string
          created_at?: string
          position?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "top_artists_artist_mbid_fkey"
            columns: ["artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "top_artists_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tracks: {
        Row: {
          duration_ms: number | null
          id: number
          position: number
          release_mbid: string
          song_mbid: string | null
          title: string
        }
        Insert: {
          duration_ms?: number | null
          id?: never
          position: number
          release_mbid: string
          song_mbid?: string | null
          title: string
        }
        Update: {
          duration_ms?: number | null
          id?: never
          position?: number
          release_mbid?: string
          song_mbid?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "tracks_release_mbid_fkey"
            columns: ["release_mbid"]
            isOneToOne: false
            referencedRelation: "releases"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "tracks_song_mbid_fkey"
            columns: ["song_mbid"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["mbid"]
          },
        ]
      }
      versus_matchups: {
        Row: {
          created_at: string
          day: string
          id: number
          left_artist_mbid: string
          right_artist_mbid: string
        }
        Insert: {
          created_at?: string
          day: string
          id?: never
          left_artist_mbid: string
          right_artist_mbid: string
        }
        Update: {
          created_at?: string
          day?: string
          id?: never
          left_artist_mbid?: string
          right_artist_mbid?: string
        }
        Relationships: [
          {
            foreignKeyName: "versus_matchups_left_artist_mbid_fkey"
            columns: ["left_artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "versus_matchups_right_artist_mbid_fkey"
            columns: ["right_artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
        ]
      }
      versus_nomination_backers: {
        Row: {
          created_at: string
          nomination_id: number
          user_id: string
        }
        Insert: {
          created_at?: string
          nomination_id: number
          user_id: string
        }
        Update: {
          created_at?: string
          nomination_id?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "versus_nomination_backers_nomination_id_fkey"
            columns: ["nomination_id"]
            isOneToOne: false
            referencedRelation: "versus_nominations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "versus_nomination_backers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      versus_nominations: {
        Row: {
          created_at: string
          id: number
          left_artist_mbid: string
          nominated_by: string
          right_artist_mbid: string
        }
        Insert: {
          created_at?: string
          id?: never
          left_artist_mbid: string
          nominated_by: string
          right_artist_mbid: string
        }
        Update: {
          created_at?: string
          id?: never
          left_artist_mbid?: string
          nominated_by?: string
          right_artist_mbid?: string
        }
        Relationships: [
          {
            foreignKeyName: "versus_nominations_left_artist_mbid_fkey"
            columns: ["left_artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
          {
            foreignKeyName: "versus_nominations_nominated_by_fkey"
            columns: ["nominated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "versus_nominations_right_artist_mbid_fkey"
            columns: ["right_artist_mbid"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["mbid"]
          },
        ]
      }
      versus_takes: {
        Row: {
          body: string
          created_at: string
          id: number
          matchup_id: number
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: never
          matchup_id: number
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: never
          matchup_id?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "versus_takes_matchup_id_fkey"
            columns: ["matchup_id"]
            isOneToOne: false
            referencedRelation: "versus_matchups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "versus_takes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      versus_votes: {
        Row: {
          created_at: string
          id: number
          matchup_id: number
          pick: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          matchup_id: number
          pick: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: never
          matchup_id?: number
          pick?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "versus_votes_matchup_id_fkey"
            columns: ["matchup_id"]
            isOneToOne: false
            referencedRelation: "versus_matchups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "versus_votes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      rate_limit_hit: {
        Args: {
          p_bucket: string
          p_subject: string
          p_limit: number
          p_window_seconds: number
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

/** A table's row, as read. */
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
/** A table's row, as written. */
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
/** A table's row, as changed. */
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
